### ISSUE TITLE
Temperature rounded

### ISSUE THREAD

**Issue by nolimitek** [danielrheinbay/fhemMAX2HASS#2]
Hello, the temperature is not transmitted accurately. It is always rounded up or down to 0.5 degrees. Is it possible to display the temperature exactly in HA

thx

regards Chris

**Comment by danielrheinbay** [comment]
Hi Chris
The temperature should get transmitted accurately. There is no rounding involved. Can you please check, e.g. using MQTTfx or mqtt_sub?
Also, what do you use to display the temperature in Home Assistant?

This is what I use:
```
features:
  - style: icons
    hvac_modes:
      - auto
      - 'off'
      - heat
    type: climate-hvac-modes
  - type: target-temperature
  - style: icons
    preset_modes:
      - eco
      - comfort
      - boost
    type: climate-preset-modes
type: tile
entity: climate.max_wallmountedthermostat_yaddayadda_someid

```
